### PR TITLE
chore(deps): update next to 13.5.6 to fix lucide-react compilation error

### PR DESCRIPTION
**Pull request by Ayc0**
Fix compilation error mentioned in https://github.com/ada-url/website/pull/100#issuecomment-2295155266

I split that in another PR to have the next update and the biome update together

Run `pnpm up next@13.5.6` to update next. I kept the v13 as I didn't want to have to tackle the migration to the v14 when this is getting migrated to Asto

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Comment by anonrig** [comment]
Perfect thank you

**Review by anonrig — APPROVED** [review]

**Comment by anonrig** [comment]
Can you solve the conflicts and rebase?

**Comment by Ayc0** [comment]
> Can you solve the conflicts and rebase?

Should be okay 👍

**Comment by anonrig** [comment]
Thank you

**Pull request merged**
