### PR TITLE
Add playground page to astro docs

### PR DESCRIPTION
**Pull request by rndexe**
Tasklist 

- [x]  Add astro integration for react
- [x] Modify shadcn components to use `utils.ts` without site config from next
- [x] Replace next specfic hooks for searchParams and replaceState with vanilla js utilities
- [x] Add support for tailwind/ Replace tailwind classNames with vanilla css
- [x] Add dropdown to select ada version for the playground

### CODE REVIEW

**Comment by anonrig** [comment]
Is it easy for you to add versioning to this playground? Basically, changing the version should change the WASM file. If we can add it, I can build Ada wasm and add those multiple files in a follow up PR

**Comment by anonrig** [comment]
we can land it with tailwindcss and remove it in a follow up pull request

**Comment by rndexe** [comment]
I don't understand the request, it is using the same wasm file as the current site. Do we need to add a choice for which wasm file to pick up? Also would it be a code based config or a url based one?

**Comment by rndexe** [comment]
Also right now tailwind is not setup to work with the astro site. I'm not sure if it'd be conflicting with the current tailwind config as it is in the same root.

Other components added earlier are also using vanilla css instead of tailwind.

**Comment by anonrig** [comment]
Let's land it with vanilla css then. I was thinking about adding a dropdown to playground with different versions (such as 2.9.0, 2.9.1 etc) which changes the version of Ada. Currently we have 1 version (only 1 wasm file) but if we add the versioning support it would be super easy to add more.

**Comment by rndexe** [comment]
Hello, I've added a drop-down for different versions. If you could add the wasm files and the corresponding wasm.js I can test the changes out.

**Pull request merged**
